// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBivR1mH_3gF71_XX6_a-J9JKBxKgiz5sA',
    appId: '1:338823151343:android:e5c7cdbb9c0d59088a251a',
    messagingSenderId: '338823151343',
    projectId: 'spotify-clone-6c58e',
    storageBucket: 'spotify-clone-6c58e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBivR1mH_3gF71_XX6_a-J9JKBxKgiz5sA',
    appId: '1:338823151343:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '338823151343',
    projectId: 'spotify-clone-6c58e',
    storageBucket: 'spotify-clone-6c58e.firebasestorage.app',
    iosBundleId: 'com.snoor.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBivR1mH_3gF71_XX6_a-J9JKBxKgiz5sA',
    appId: '1:338823151343:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '338823151343',
    projectId: 'spotify-clone-6c58e',
    storageBucket: 'spotify-clone-6c58e.firebasestorage.app',
    iosBundleId: 'com.snoor.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBivR1mH_3gF71_XX6_a-J9JKBxKgiz5sA',
    appId: '1:338823151343:windows:YOUR_WINDOWS_APP_ID',
    messagingSenderId: '338823151343',
    projectId: 'spotify-clone-6c58e',
    storageBucket: 'spotify-clone-6c58e.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBivR1mH_3gF71_XX6_a-J9JKBxKgiz5sA',
    appId: '1:338823151343:linux:YOUR_LINUX_APP_ID',
    messagingSenderId: '338823151343',
    projectId: 'spotify-clone-6c58e',
    storageBucket: 'spotify-clone-6c58e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBivR1mH_3gF71_XX6_a-J9JKBxKgiz5sA',
    appId: '1:338823151343:web:YOUR_WEB_APP_ID',
    messagingSenderId: '338823151343',
    projectId: 'spotify-clone-6c58e',
    storageBucket: 'spotify-clone-6c58e.firebasestorage.app',
  );
}
